### ISSUE TITLE
Release v2 of packages

### ISSUE THREAD

**Issue by ubermanu** [stylelint-less/stylelint-less#10]
Hey guys,

I need @crazyurus and @ssivanatarajan to give me publish access to your packages on NPM, so I can release the v2 of these:

- [x] stylelint-less
- [x] stylelint-config-recommended-less
- [x] stylelint-config-standard-less

**Comment by crazyurus** [comment]
Ok. Please provide your npm username.  I will add it later.

**Comment by ubermanu** [comment]
@crazyurus my NPM account: https://www.npmjs.com/~ubermanu

**Comment by crazyurus** [comment]
> @crazyurus my NPM account: https://www.npmjs.com/~ubermanu

Done

**Comment by ssivanatarajan** [comment]
> @crazyurus my NPM account: https://www.npmjs.com/~ubermanu

@ubermanu Sent invitation.

**Comment by ubermanu** [comment]
Alright I published v2 of the 3 packages on NPM 👍

I also tossed you another invite to the org @ssivanatarajan (it has a 7 days ttl)
